sudo: false
dist: trusty
jdk:
  - openjdk8
before_script:
  - echo "MAVEN_OPTS='-Xmx512m -XX:MaxPermSize=256m'" > ~/.mavenrc
script:
  - mvn clean install -Pextjs,h2_disk,auditing
after_success:
  - mvn clean cobertura:cobertura coveralls:report sonar:sonar -Dsonar.projectKey=Gnafu_geostore
addons:
  sonarcloud:
    organization: "gnafu"